global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    metrics_path: /metrics
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "user-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["user-service:5000"]

  - job_name: "order-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["order-service:4002"]

  - job_name: "product-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["product-service:80"]
